apiVersion: v1
kind: Pod
metadata:
  name: pvc-access-pod
spec:
  containers:
  - name: busybox
    image: busybox
    command: ['sh', '-c', 'sleep 3600'] # Keep the pod alive for 1 hour
    volumeMounts:
    - mountPath: "/data"
      name: backup-volume
  volumes:
  - name: backup-volume
    persistentVolumeClaim:
      claimName: etcd-backup-pvc
